---
- name: Install Grafana
  hosts: all
  become: true
  tasks:
  
    - name: update repo
      apt:
        update_cache: true
        name: gnupg
        state: present

    - name: Import the GPG key
      ansible.builtin.apt_key:
        url: https://packages.grafana.com/gpg.key
        state: present

    - name: Update repositories and install Grafana
      ansible.builtin.apt:
        update_cache: yes
        name: grafana
        state: latest

    - name: Update apt and install Grafana
      apt:
        name: grafana
        state: present

    # Optionally, you may need to start and enable Grafana service
    - name: Start Grafana service
      service:
        name: grafana-server
        state: started
        enabled: yes