--- 
- name: Prometheus
  hosts: all
  become: true
  tasks:

    - name: update repo
      apt:
        update_cache: true

    - name: Installtion
      ansible.builtin.apt:
        pkg: prometheus
        state: present

    - name: Start prometheus
      ansible.builtin.service:
        name: prometheus
        state: started 
        enabled: yes
